/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationConnection } from './automation-connection';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationStep } from './automation-step';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationVersionDto } from './automation-version-dto';

/**
 * 
 * @export
 * @interface AutomationDto
 */
export interface AutomationDto {
    /**
     * 
     * @type {Array<AutomationStep>}
     * @memberof AutomationDto
     */
    'steps': Array<AutomationStep>;
    /**
     * 
     * @type {Array<AutomationConnection>}
     * @memberof AutomationDto
     */
    'connections': Array<AutomationConnection>;
    /**
     * 
     * @type {AutomationVersionDto}
     * @memberof AutomationDto
     */
    'version': AutomationVersionDto;
    /**
     * 
     * @type {string}
     * @memberof AutomationDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationDto
     */
    'status': AutomationDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AutomationDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationDto
     */
    'updatedAt': string;
}

export const AutomationDtoStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;

export type AutomationDtoStatusEnum = typeof AutomationDtoStatusEnum[keyof typeof AutomationDtoStatusEnum];


