/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationBaseDto } from './automation-base-dto';

/**
 * 
 * @export
 * @interface AutomationsPaginatedDto
 */
export interface AutomationsPaginatedDto {
    /**
     * 
     * @type {number}
     * @memberof AutomationsPaginatedDto
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof AutomationsPaginatedDto
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof AutomationsPaginatedDto
     */
    'offset': number;
    /**
     * 
     * @type {Array<AutomationBaseDto>}
     * @memberof AutomationsPaginatedDto
     */
    'results': Array<AutomationBaseDto>;
}

