/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationConnection } from './automation-connection';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationStep } from './automation-step';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationTrigger } from './automation-trigger';

/**
 * 
 * @export
 * @interface AutomationVersion
 */
export interface AutomationVersion {
    /**
     * 
     * @type {string}
     * @memberof AutomationVersion
     */
    'id': string;
    /**
     * 
     * @type {AutomationTrigger}
     * @memberof AutomationVersion
     */
    'trigger': AutomationTrigger;
    /**
     * 
     * @type {Array<AutomationStep>}
     * @memberof AutomationVersion
     */
    'steps': Array<AutomationStep>;
    /**
     * 
     * @type {Array<AutomationConnection>}
     * @memberof AutomationVersion
     */
    'connections': Array<AutomationConnection>;
    /**
     * 
     * @type {string}
     * @memberof AutomationVersion
     */
    'publishedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AutomationVersion
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationVersion
     */
    'updatedAt': string;
}

