/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Automation
 */
export interface Automation {
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'publishedVersionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'draftVersionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'status': AutomationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'updatedAt': string;
}

export const AutomationStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;

export type AutomationStatusEnum = typeof AutomationStatusEnum[keyof typeof AutomationStatusEnum];


