/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Automation } from './automation';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationVersion } from './automation-version';

/**
 * 
 * @export
 * @interface AutomationResponseDto
 */
export interface AutomationResponseDto {
    /**
     * 
     * @type {Automation}
     * @memberof AutomationResponseDto
     */
    'automation': Automation;
    /**
     * 
     * @type {AutomationVersion}
     * @memberof AutomationResponseDto
     */
    'publishedVersion'?: AutomationVersion;
    /**
     * 
     * @type {AutomationVersion}
     * @memberof AutomationResponseDto
     */
    'draftVersion'?: AutomationVersion;
}

