/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationVersionOverviewDto } from './automation-version-overview-dto';

/**
 * 
 * @export
 * @interface AutomationOverviewDto
 */
export interface AutomationOverviewDto {
    /**
     * 
     * @type {AutomationVersionOverviewDto}
     * @memberof AutomationOverviewDto
     */
    'publishedVersion'?: AutomationVersionOverviewDto;
    /**
     * 
     * @type {AutomationVersionOverviewDto}
     * @memberof AutomationOverviewDto
     */
    'draftVersion'?: AutomationVersionOverviewDto;
    /**
     * 
     * @type {string}
     * @memberof AutomationOverviewDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationOverviewDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationOverviewDto
     */
    'status': AutomationOverviewDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AutomationOverviewDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationOverviewDto
     */
    'updatedAt': string;
}

export const AutomationOverviewDtoStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;

export type AutomationOverviewDtoStatusEnum = typeof AutomationOverviewDtoStatusEnum[keyof typeof AutomationOverviewDtoStatusEnum];


