/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AutomationStepPosition
 */
export interface AutomationStepPosition {
    /**
     * 
     * @type {number}
     * @memberof AutomationStepPosition
     */
    'x': number;
    /**
     * 
     * @type {number}
     * @memberof AutomationStepPosition
     */
    'y': number;
}

