/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationStepsInner } from './automation-steps-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { Connection } from './connection';

/**
 * 
 * @export
 * @interface Automation
 */
export interface Automation {
    /**
     * 
     * @type {string}
     * @memberof Automation
     */
    'name': string;
    /**
     * 
     * @type {Array<AutomationStepsInner>}
     * @memberof Automation
     */
    'steps': Array<AutomationStepsInner>;
    /**
     * 
     * @type {Array<Connection>}
     * @memberof Automation
     */
    'connections': Array<Connection>;
}

