/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TelegramSendMessageTask } from './telegram-send-message-task';
// May contain unused imports in some cases
// @ts-ignore
import type { TriggerReceivedMessageTask } from './trigger-received-message-task';

/**
 * 
 * @export
 * @interface AutomationTask
 */
export interface AutomationTask {
    /**
     * 
     * @type {TriggerReceivedMessageTask}
     * @memberof AutomationTask
     */
    'trigger_receivedMessage'?: TriggerReceivedMessageTask;
    /**
     * 
     * @type {TelegramSendMessageTask}
     * @memberof AutomationTask
     */
    'action_telegram_sendMessage'?: TelegramSendMessageTask;
}

