/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AutomationBaseDto
 */
export interface AutomationBaseDto {
    /**
     * 
     * @type {string}
     * @memberof AutomationBaseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationBaseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationBaseDto
     */
    'status': AutomationBaseDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AutomationBaseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AutomationBaseDto
     */
    'updatedAt': string;
}

export const AutomationBaseDtoStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;

export type AutomationBaseDtoStatusEnum = typeof AutomationBaseDtoStatusEnum[keyof typeof AutomationBaseDtoStatusEnum];


