/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateStepPositionsDto } from './update-step-positions-dto';

/**
 * 
 * @export
 * @interface BulkUpdateStepPositionsDto
 */
export interface BulkUpdateStepPositionsDto {
    /**
     * 
     * @type {Array<UpdateStepPositionsDto>}
     * @memberof BulkUpdateStepPositionsDto
     */
    'steps': Array<UpdateStepPositionsDto>;
}

