/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChannelDto
 */
export interface ChannelDto {
    /**
     * 
     * @type {string}
     * @memberof ChannelDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ChannelDto
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ChannelDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ChannelDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ChannelDto
     */
    'updatedAt': string;
}

