/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Connection
 */
export interface Connection {
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'sourceStepId': string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'sourceHandleId': string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'targetStepId': string;
    /**
     * 
     * @type {string}
     * @memberof Connection
     */
    'targetHandleId': string;
}

