/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TriggerReceivedMessageTask } from './trigger-received-message-task';

/**
 * 
 * @export
 * @interface CreateAutomationDto
 */
export interface CreateAutomationDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAutomationDto
     */
    'name': string;
    /**
     * 
     * @type {TriggerReceivedMessageTask}
     * @memberof CreateAutomationDto
     */
    'trigger'?: TriggerReceivedMessageTask;
}

