/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteConnectionsDto
 */
export interface DeleteConnectionsDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteConnectionsDto
     */
    'connectionIds': Array<string>;
}

