/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Automation } from './automation';

/**
 * 
 * @export
 * @interface PaginatedAutomationsDto
 */
export interface PaginatedAutomationsDto {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAutomationsDto
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedAutomationsDto
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedAutomationsDto
     */
    'offset': number;
    /**
     * 
     * @type {Array<Automation>}
     * @memberof PaginatedAutomationsDto
     */
    'results': Array<Automation>;
}

