/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StepTelegramSendMessage
 */
export interface StepTelegramSendMessage {
    /**
     * Discriminator field to determine the type of step
     * @type {string}
     * @memberof StepTelegramSendMessage
     */
    'type': StepTelegramSendMessageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof StepTelegramSendMessage
     */
    'message': string;
}

export const StepTelegramSendMessageTypeEnum = {
    StepTelegramSendMessage: 'StepTelegramSendMessage'
} as const;

export type StepTelegramSendMessageTypeEnum = typeof StepTelegramSendMessageTypeEnum[keyof typeof StepTelegramSendMessageTypeEnum];


