/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StepTelegramCheckSubscription
 */
export interface StepTelegramCheckSubscription {
    /**
     * Discriminator field to determine the type of step
     * @type {string}
     * @memberof StepTelegramCheckSubscription
     */
    'type': StepTelegramCheckSubscriptionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof StepTelegramCheckSubscription
     */
    'channelId': string;
}

export const StepTelegramCheckSubscriptionTypeEnum = {
    StepTelegramCheckSubscription: 'StepTelegramCheckSubscription'
} as const;

export type StepTelegramCheckSubscriptionTypeEnum = typeof StepTelegramCheckSubscriptionTypeEnum[keyof typeof StepTelegramCheckSubscriptionTypeEnum];


