/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TelegramTimeout
 */
export interface TelegramTimeout {
    /**
     * 
     * @type {number}
     * @memberof TelegramTimeout
     */
    'duration': number;
    /**
     * 
     * @type {string}
     * @memberof TelegramTimeout
     */
    'unit': string;
}

