/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TelegramQuickReplyButton
 */
export interface TelegramQuickReplyButton {
    /**
     * 
     * @type {string}
     * @memberof TelegramQuickReplyButton
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TelegramQuickReplyButton
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof TelegramQuickReplyButton
     */
    'url'?: string;
}

