/* tslint:disable */
/* eslint-disable */
/**
 * Autobot API
 * Autobot API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StepPositionDto } from './step-position-dto';

/**
 * 
 * @export
 * @interface UpdateStepsPositionsDto
 */
export interface UpdateStepsPositionsDto {
    /**
     * 
     * @type {Array<StepPositionDto>}
     * @memberof UpdateStepsPositionsDto
     */
    'steps': Array<StepPositionDto>;
}

